// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcbcwf0LOEiImwaY7Ty6iLmMHt3WLpcMY',
    appId: '1:202846961309:web:19ae7f243304eb6d6c9e74',
    messagingSenderId: '202846961309',
    projectId: 'night-music-tought',
    authDomain: 'night-music-tought.firebaseapp.com',
    storageBucket: 'night-music-tought.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN15SK0scU3wyWFXCgpKQ-pzxqbV3cj5A',
    appId: '1:202846961309:android:a5709afa14157d176c9e74',
    messagingSenderId: '202846961309',
    projectId: 'night-music-tought',
    storageBucket: 'night-music-tought.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyp5dYRQQHZoXra17yXr4eInbhGQbRMYQ',
    appId: '1:202846961309:ios:2bf63351cdf26d3f6c9e74',
    messagingSenderId: '202846961309',
    projectId: 'night-music-tought',
    storageBucket: 'night-music-tought.firebasestorage.app',
    iosBundleId: 'com.example.nighttrack',
  );
}
